spring:
  application:
    name: julio

  datasource:
    url: jdbc:postgresql://localhost:5432/financas
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  loggin:
    level:
      root: WARN
      com.financas.julio: INFO